export const FILTER_EMPLOYEES = 'FILTER_EMPLOYEES';
export const CLEAR_FILTER = 'CLEAR_FILTER';
export const GET_EMPLOYEES = 'GET_EMPLOYEES';
export const EMPLOYEE_ERROR = 'EMPLOYEE_ERROR';
export const CLEAR_CURRENT = 'CLEAR_CURRENT';
export const SET_CURRENT = 'SET_CURRENT';
export const SCHEDULE_MEETING = 'SCHEDULE_MEETING';
export const SET_LOADING = 'SET_LOADING';
export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';
export const CLEAR_USERS = 'CLEAR_USERS'; //remove later
export const GET_REPOS = 'GET_REPOS'; //remove later
export const GET_USERS = 'GET_USERS'; //remove later
export const SEARCH_USERS = 'SEARCH_USERS'; //remove later